# Generated by Django 3.2.12 on 2022-08-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tast',
            options={'ordering': ['complete', '-created']},
        ),
        migrations.AddField(
            model_name='tast',
            name='slud',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
