# Generated by Django 3.2.12 on 2022-08-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220829_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tast',
            old_name='slud',
            new_name='slug',
        ),
    ]
